### ISSUE TITLE
ESP32-S2 Implementation

### ISSUE THREAD

**Issue by EstebanFuentealba** [furrtek/GBCamcorder#4]
Hello, I've been trying to capture an image from a GB Camera using an ESP32-S2 (240MHz) for the past few days. I've connected all the cartridge pins to the ESP32, and after making some modifications to your code, I've come up with the following code snippet:

```c

#define GAMEBOY_CLK 12   //    (FSPICLK)(SCLK)SCK
#define GAMEBOY_WR 13    //    (FSPIQ)(DC)MISO
#define GAMEBOY_RD 11    //     (FSPID)(SDA)MOSI
#define GAMEBOY_CS 10    //     (FSPICS0)(CS)SS

// Address Pins
#define GAMEBOY_A00 42 
#define GAMEBOY_A01 41  
#define GAMEBOY_A02 33  
#define GAMEBOY_A03 34  
#define GAMEBOY_A04 35 
#define GAMEBOY_A05 36  //       (FSPIQ)(DC)MISO
#define GAMEBOY_A06 37  //       (FSPICLK)(SCLK)SCK
#define GAMEBOY_A07 38  //       (FSPID)(SDA)MOSI

#define GAMEBOY_A08 39  //      (FSPICS0)(CS)SS
#define GAMEBOY_A09 40  //
#define GAMEBOY_A10 26  //
#define GAMEBOY_A11 21  //
#define GAMEBOY_A12 20  //
#define GAMEBOY_A13 19  //
#define GAMEBOY_A14 16  //      
#define GAMEBOY_A15 15  //  

// Data Pins
#define GAMEBOY_D00 14   //  (SCL)
#define GAMEBOY_D01 9   //    (SDA)
#define GAMEBOY_D02 8   
#define GAMEBOY_D03 7 
#define GAMEBOY_D04 6  
#define GAMEBOY_D05 5  
#define GAMEBOY_D06 4  
#define GAMEBOY_D07 3 

#define GAMEBOY_RST 2   //  RESET
#define GAMEBOY_AUDIO 1  


// ...

// Clear GB Cam scratchpad RAM (bank 0, A000~AFFF)
cart_put(0x4000, 0x00);		// SRAM bank 0
cart_put(0x0000, 0x0A);		// Enable SRAM writes

// Ask ASIC for capture
cart_put(0x4000, 0x10);	// ASIC registers
delay_us(2);
cart_put(0xA000, 0x03);

// Wait for capture to start
gbcam_wait_busy();

//  Read
// ...
```

I thought this code would be sufficient to capture an image, but I haven't succeeded yet. However, I have been able to read the RAM to view the last capture (I tested it by capturing an image from the Gameboy using the cartridge).

Now, I have some questions:

Is it necessary to connect phi, rd, wr, cs to SPI pins, or can they be connected to any other pins?
Do you believe it's possible to implement this on an ESP32-S2?
How do you ensure that the processor speeds between the STM32 and the Gameboy are matched?

I'm sorry, I'm very new to electronics 🙏.

**Comment by furrtek** [comment]
Hi,
Any GPIO would do, it's a parallel bus so there's no need for SPI.
The GB camera is one of the few carts that needs the Phi clock to work properly, it should be == to the GB CPU clock.
Wr, Rd, Cs must of course be asserted at the right times for read and write ops.
There's no minimal speed but there's a max. As long as you stay within GB speeds you should be fine.
